/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * CommunicationType.h
 *
 * Possible values are - REQUEST_RESPONSE: The communication is of the type
 * request-response - SUBSCRIBE_NOTIFY: The communication is of the type
 * subscribe-notify
 */

#ifndef CommunicationType_H_
#define CommunicationType_H_

#include <nlohmann/json.hpp>

#include "capif/model/CommunicationType_anyOf.h"

namespace org::openapitools::server::model {

/// <summary>
/// Possible values are - REQUEST_RESPONSE: The communication is of the type
/// request-response - SUBSCRIBE_NOTIFY: The communication is of the type
/// subscribe-notify
/// </summary>
class CommunicationType {
 public:
  CommunicationType();
  virtual ~CommunicationType() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const CommunicationType& rhs) const;
  bool operator!=(const CommunicationType& rhs) const;

  /////////////////////////////////////////////
  /// CommunicationType members

  CommunicationType_anyOf getValue() const;
  void setValue(CommunicationType_anyOf value);
  CommunicationType_anyOf::eCommunicationType_anyOf getEnumValue() const;
  void setEnumValue(CommunicationType_anyOf::eCommunicationType_anyOf value);
  friend void to_json(nlohmann::json& j, const CommunicationType& o);
  friend void from_json(const nlohmann::json& j, CommunicationType& o);
  friend void to_json(nlohmann::json& j, const CommunicationType_anyOf& o);
  friend void from_json(const nlohmann::json& j, CommunicationType_anyOf& o);

 protected:
  CommunicationType_anyOf m_value;
};

}  // namespace org::openapitools::server::model

#endif /* CommunicationType_H_ */
