/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DataFormat.h
 *
 * Possible values are - JSON: JavaScript Object Notation
 */

#ifndef DataFormat_H_
#define DataFormat_H_

#include <nlohmann/json.hpp>

#include "capif/model/DataFormat_anyOf.h"

namespace org::openapitools::server::model {

/// <summary>
/// Possible values are - JSON: JavaScript Object Notation
/// </summary>
class DataFormat {
 public:
  DataFormat();
  virtual ~DataFormat() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const DataFormat& rhs) const;
  bool operator!=(const DataFormat& rhs) const;

  /////////////////////////////////////////////
  /// DataFormat members

  DataFormat_anyOf getValue() const;
  void setValue(DataFormat_anyOf value);
  DataFormat_anyOf::eDataFormat_anyOf getEnumValue() const;
  void setEnumValue(DataFormat_anyOf::eDataFormat_anyOf value);
  friend void to_json(nlohmann::json& j, const DataFormat& o);
  friend void from_json(const nlohmann::json& j, DataFormat& o);
  friend void to_json(nlohmann::json& j, const DataFormat_anyOf& o);
  friend void from_json(const nlohmann::json& j, DataFormat_anyOf& o);

 protected:
  DataFormat_anyOf m_value;
};

}  // namespace org::openapitools::server::model

#endif /* DataFormat_H_ */
