/**
 * CAPIF_Discover_Service_API
 * API for discovering service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Protocol_anyOf.h
 *
 *
 */

#ifndef Protocol_anyOf_H_
#define Protocol_anyOf_H_

#include <nlohmann/json.hpp>

namespace org::openapitools::server::model {

/// <summary>
///
/// </summary>
class Protocol_anyOf {
 public:
  Protocol_anyOf();
  virtual ~Protocol_anyOf() = default;

  enum class eProtocol_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    _1_1,
    _2
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const Protocol_anyOf& rhs) const;
  bool operator!=(const Protocol_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// Protocol_anyOf members

  Protocol_anyOf::eProtocol_anyOf getValue() const;
  void setValue(Protocol_anyOf::eProtocol_anyOf value);

  friend void to_json(nlohmann::json& j, const Protocol_anyOf& o);
  friend void from_json(const nlohmann::json& j, Protocol_anyOf& o);

 protected:
  Protocol_anyOf::eProtocol_anyOf m_value =
      Protocol_anyOf::eProtocol_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace org::openapitools::server::model

#endif /* Protocol_anyOf_H_ */
