/**
 * Merged 3GPP CAPIF API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: h20
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
#include "DefaultApiImpl.h"

namespace org::openapitools::server::api
{

    using namespace org::openapitools::server::model;

    DefaultApiImpl::DefaultApiImpl(const std::shared_ptr<Pistache::Rest::Router> &rtr,
                                   const std::shared_ptr<mongocxx::database> &database)
        : DefaultApi(rtr), db(database)
    {
        api_collection = (*db)["apis"];
    }

    
    
    
    
    
    
}
