/**
* CAPIF_Publish_Service_API
* API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "DataFormat.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

DataFormat::DataFormat()
{
    
}

void DataFormat::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool DataFormat::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool DataFormat::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "DataFormat" : pathPrefix;

    
    if (!m_value.validate(msg))
    {
        success = false;
    }
    return success;
}

bool DataFormat::operator==(const DataFormat& rhs) const
{
    return
    
    getValue() == rhs.getValue()
    ;
}

bool DataFormat::operator!=(const DataFormat& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const DataFormat& o)
{
    j = nlohmann::json();
    to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, DataFormat& o)
{
    from_json(j, o.m_value);
}

DataFormat_anyOf DataFormat::getValue() const
{
    return m_value;
}

void DataFormat::setValue(DataFormat_anyOf value)
{
    m_value = value;
}

DataFormat_anyOf::eDataFormat_anyOf DataFormat::getEnumValue() const
{
    return m_value.getValue();
}

void DataFormat::setEnumValue(DataFormat_anyOf::eDataFormat_anyOf  value)
{
    m_value.setValue(value);
}

} // namespace org::openapitools::server::model

