/**
* CAPIF_Publish_Service_API
* API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Protocol_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace org::openapitools::server::model
{

Protocol_anyOf::Protocol_anyOf()
{
    
}

void Protocol_anyOf::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Protocol_anyOf::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Protocol_anyOf::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Protocol_anyOf" : pathPrefix;

    
    if (m_value == Protocol_anyOf::eProtocol_anyOf::INVALID_VALUE_OPENAPI_GENERATED)
    {
        success = false;
        msg << _pathPrefix << ": has no value;";
    }

    return success;
}

bool Protocol_anyOf::operator==(const Protocol_anyOf& rhs) const
{
    return
    getValue() == rhs.getValue()
    
    ;
}

bool Protocol_anyOf::operator!=(const Protocol_anyOf& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Protocol_anyOf& o)
{
    j = nlohmann::json();
    
    switch (o.getValue())
    {
        case Protocol_anyOf::eProtocol_anyOf::INVALID_VALUE_OPENAPI_GENERATED:
            j = "INVALID_VALUE_OPENAPI_GENERATED";
            break;
        case Protocol_anyOf::eProtocol_anyOf::_1_1:
            j = "HTTP_1_1";
            break;
        case Protocol_anyOf::eProtocol_anyOf::_2:
            j = "HTTP_2";
            break;
    }
}

void from_json(const nlohmann::json& j, Protocol_anyOf& o)
{
    
    auto s = j.get<std::string>();
    if (s == "HTTP_1_1") {
     o.setValue(Protocol_anyOf::eProtocol_anyOf::_1_1);
    } 
    else if (s == "HTTP_2") {
     o.setValue(Protocol_anyOf::eProtocol_anyOf::_2);
    }  else {
     std::stringstream ss;
     ss << "Unexpected value " << s << " in json"
        << " cannot be converted to enum of type"
        << " Protocol_anyOf::eProtocol_anyOf";
     throw std::invalid_argument(ss.str());
    } 

}

Protocol_anyOf::eProtocol_anyOf Protocol_anyOf::getValue() const
{
    return m_value;
}
void Protocol_anyOf::setValue(Protocol_anyOf::eProtocol_anyOf value)
{
    m_value = value;
}

} // namespace org::openapitools::server::model

