/**
* CAPIF_Publish_Service_API
* API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Resource.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Resource::Resource()
{
    m_ResourceName = "";
    m_Uri = "";
    m_CustOpName = "";
    m_CustOpNameIsSet = false;
    m_OperationsIsSet = false;
    m_Description = "";
    m_DescriptionIsSet = false;
    
}

void Resource::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Resource::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Resource::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Resource" : pathPrefix;

                         
    if (operationsIsSet())
    {
        const std::vector<Operation>& value = m_Operations;
        const std::string currentValuePath = _pathPrefix + ".operations";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const Operation& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".operations") && success;
 
                i++;
            }
        }

    }
        
    return success;
}

bool Resource::operator==(const Resource& rhs) const
{
    return
    
    
    (getResourceName() == rhs.getResourceName())
     &&
    
    (getCommType() == rhs.getCommType())
     &&
    
    (getUri() == rhs.getUri())
     &&
    
    
    ((!custOpNameIsSet() && !rhs.custOpNameIsSet()) || (custOpNameIsSet() && rhs.custOpNameIsSet() && getCustOpName() == rhs.getCustOpName())) &&
    
    
    ((!operationsIsSet() && !rhs.operationsIsSet()) || (operationsIsSet() && rhs.operationsIsSet() && getOperations() == rhs.getOperations())) &&
    
    
    ((!descriptionIsSet() && !rhs.descriptionIsSet()) || (descriptionIsSet() && rhs.descriptionIsSet() && getDescription() == rhs.getDescription()))
    
    ;
}

bool Resource::operator!=(const Resource& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Resource& o)
{
    j = nlohmann::json();
    j["resourceName"] = o.m_ResourceName;
    j["commType"] = o.m_CommType;
    j["uri"] = o.m_Uri;
    if(o.custOpNameIsSet())
        j["custOpName"] = o.m_CustOpName;
    if(o.operationsIsSet() || !o.m_Operations.empty())
        j["operations"] = o.m_Operations;
    if(o.descriptionIsSet())
        j["description"] = o.m_Description;
    
}

void from_json(const nlohmann::json& j, Resource& o)
{
    j.at("resourceName").get_to(o.m_ResourceName);
    j.at("commType").get_to(o.m_CommType);
    j.at("uri").get_to(o.m_Uri);
    if(j.find("custOpName") != j.end())
    {
        j.at("custOpName").get_to(o.m_CustOpName);
        o.m_CustOpNameIsSet = true;
    } 
    if(j.find("operations") != j.end())
    {
        j.at("operations").get_to(o.m_Operations);
        o.m_OperationsIsSet = true;
    } 
    if(j.find("description") != j.end())
    {
        j.at("description").get_to(o.m_Description);
        o.m_DescriptionIsSet = true;
    } 
    
}

std::string Resource::getResourceName() const
{
    return m_ResourceName;
}
void Resource::setResourceName(std::string const& value)
{
    m_ResourceName = value;
}
CommunicationType Resource::getCommType() const
{
    return m_CommType;
}
void Resource::setCommType(CommunicationType const& value)
{
    m_CommType = value;
}
std::string Resource::getUri() const
{
    return m_Uri;
}
void Resource::setUri(std::string const& value)
{
    m_Uri = value;
}
std::string Resource::getCustOpName() const
{
    return m_CustOpName;
}
void Resource::setCustOpName(std::string const& value)
{
    m_CustOpName = value;
    m_CustOpNameIsSet = true;
}
bool Resource::custOpNameIsSet() const
{
    return m_CustOpNameIsSet;
}
void Resource::unsetCustOpName()
{
    m_CustOpNameIsSet = false;
}
std::vector<Operation> Resource::getOperations() const
{
    return m_Operations;
}
void Resource::setOperations(std::vector<Operation> const& value)
{
    m_Operations = value;
    m_OperationsIsSet = true;
}
bool Resource::operationsIsSet() const
{
    return m_OperationsIsSet;
}
void Resource::unsetOperations()
{
    m_OperationsIsSet = false;
}
std::string Resource::getDescription() const
{
    return m_Description;
}
void Resource::setDescription(std::string const& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}
bool Resource::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}
void Resource::unsetDescription()
{
    m_DescriptionIsSet = false;
}


} // namespace org::openapitools::server::model

