/**
* CAPIF_Publish_Service_API
* API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SecurityMethod_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace org::openapitools::server::model
{

SecurityMethod_anyOf::SecurityMethod_anyOf()
{
    
}

void SecurityMethod_anyOf::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool SecurityMethod_anyOf::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool SecurityMethod_anyOf::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "SecurityMethod_anyOf" : pathPrefix;

    
    if (m_value == SecurityMethod_anyOf::eSecurityMethod_anyOf::INVALID_VALUE_OPENAPI_GENERATED)
    {
        success = false;
        msg << _pathPrefix << ": has no value;";
    }

    return success;
}

bool SecurityMethod_anyOf::operator==(const SecurityMethod_anyOf& rhs) const
{
    return
    getValue() == rhs.getValue()
    
    ;
}

bool SecurityMethod_anyOf::operator!=(const SecurityMethod_anyOf& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SecurityMethod_anyOf& o)
{
    j = nlohmann::json();
    
    switch (o.getValue())
    {
        case SecurityMethod_anyOf::eSecurityMethod_anyOf::INVALID_VALUE_OPENAPI_GENERATED:
            j = "INVALID_VALUE_OPENAPI_GENERATED";
            break;
        case SecurityMethod_anyOf::eSecurityMethod_anyOf::PSK:
            j = "PSK";
            break;
        case SecurityMethod_anyOf::eSecurityMethod_anyOf::PKI:
            j = "PKI";
            break;
        case SecurityMethod_anyOf::eSecurityMethod_anyOf::OAUTH:
            j = "OAUTH";
            break;
    }
}

void from_json(const nlohmann::json& j, SecurityMethod_anyOf& o)
{
    
    auto s = j.get<std::string>();
    if (s == "PSK") {
     o.setValue(SecurityMethod_anyOf::eSecurityMethod_anyOf::PSK);
    } 
    else if (s == "PKI") {
     o.setValue(SecurityMethod_anyOf::eSecurityMethod_anyOf::PKI);
    } 
    else if (s == "OAUTH") {
     o.setValue(SecurityMethod_anyOf::eSecurityMethod_anyOf::OAUTH);
    }  else {
     std::stringstream ss;
     ss << "Unexpected value " << s << " in json"
        << " cannot be converted to enum of type"
        << " SecurityMethod_anyOf::eSecurityMethod_anyOf";
     throw std::invalid_argument(ss.str());
    } 

}

SecurityMethod_anyOf::eSecurityMethod_anyOf SecurityMethod_anyOf::getValue() const
{
    return m_value;
}
void SecurityMethod_anyOf::setValue(SecurityMethod_anyOf::eSecurityMethod_anyOf value)
{
    m_value = value;
}

} // namespace org::openapitools::server::model

