/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "capif/model/CommunicationType.h"

#include <sstream>

#include "capif/model/Helpers.h"

namespace org::openapitools::server::model {

CommunicationType::CommunicationType() {}

void CommunicationType::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool CommunicationType::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool CommunicationType::validate(std::stringstream& msg,
                                 const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "CommunicationType" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool CommunicationType::operator==(const CommunicationType& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool CommunicationType::operator!=(const CommunicationType& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CommunicationType& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, CommunicationType& o) {
  from_json(j, o.m_value);
}

CommunicationType_anyOf CommunicationType::getValue() const { return m_value; }

void CommunicationType::setValue(CommunicationType_anyOf value) {
  m_value = value;
}

CommunicationType_anyOf::eCommunicationType_anyOf
CommunicationType::getEnumValue() const {
  return m_value.getValue();
}

void CommunicationType::setEnumValue(
    CommunicationType_anyOf::eCommunicationType_anyOf value) {
  m_value.setValue(value);
}

}  // namespace org::openapitools::server::model
