/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "capif/model/Operation.h"

#include <sstream>

#include "capif/model/Helpers.h"

namespace org::openapitools::server::model {

Operation::Operation() {}

void Operation::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool Operation::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Operation::validate(std::stringstream& msg,
                         const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "Operation" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool Operation::operator==(const Operation& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool Operation::operator!=(const Operation& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Operation& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, Operation& o) {
  from_json(j, o.m_value);
}

Operation_anyOf Operation::getValue() const { return m_value; }

void Operation::setValue(Operation_anyOf value) { m_value = value; }

Operation_anyOf::eOperation_anyOf Operation::getEnumValue() const {
  return m_value.getValue();
}

void Operation::setEnumValue(Operation_anyOf::eOperation_anyOf value) {
  m_value.setValue(value);
}

}  // namespace org::openapitools::server::model
