/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "capif/model/Protocol.h"

#include <sstream>

#include "capif/model/Helpers.h"

namespace org::openapitools::server::model {

Protocol::Protocol() {}

void Protocol::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool Protocol::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Protocol::validate(std::stringstream& msg,
                        const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "Protocol" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool Protocol::operator==(const Protocol& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool Protocol::operator!=(const Protocol& rhs) const { return !(*this == rhs); }

void to_json(nlohmann::json& j, const Protocol& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, Protocol& o) {
  from_json(j, o.m_value);
}

Protocol_anyOf Protocol::getValue() const { return m_value; }

void Protocol::setValue(Protocol_anyOf value) { m_value = value; }

Protocol_anyOf::eProtocol_anyOf Protocol::getEnumValue() const {
  return m_value.getValue();
}

void Protocol::setEnumValue(Protocol_anyOf::eProtocol_anyOf value) {
  m_value.setValue(value);
}

}  // namespace org::openapitools::server::model
