/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "capif/model/SecurityMethod.h"

#include <sstream>

#include "capif/model/Helpers.h"

namespace org::openapitools::server::model {

SecurityMethod::SecurityMethod() {}

void SecurityMethod::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool SecurityMethod::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SecurityMethod::validate(std::stringstream& msg,
                              const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SecurityMethod" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool SecurityMethod::operator==(const SecurityMethod& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool SecurityMethod::operator!=(const SecurityMethod& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SecurityMethod& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, SecurityMethod& o) {
  from_json(j, o.m_value);
}

SecurityMethod_anyOf SecurityMethod::getValue() const { return m_value; }

void SecurityMethod::setValue(SecurityMethod_anyOf value) { m_value = value; }

SecurityMethod_anyOf::eSecurityMethod_anyOf SecurityMethod::getEnumValue()
    const {
  return m_value.getValue();
}

void SecurityMethod::setEnumValue(
    SecurityMethod_anyOf::eSecurityMethod_anyOf value) {
  m_value.setValue(value);
}

}  // namespace org::openapitools::server::model
