/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "capif/model/ShareableInformation.h"

#include <sstream>

#include "capif/model/Helpers.h"

namespace org::openapitools::server::model {

ShareableInformation::ShareableInformation() {
  m_IsShareable = false;
  m_CapifProvDomsIsSet = false;
}

void ShareableInformation::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool ShareableInformation::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ShareableInformation::validate(std::stringstream& msg,
                                    const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ShareableInformation" : pathPrefix;

  if (capifProvDomsIsSet()) {
    const std::vector<std::string>& value = m_CapifProvDoms;
    const std::string currentValuePath = _pathPrefix + ".capifProvDoms";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i = 0;
      for (const std::string& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  return success;
}

bool ShareableInformation::operator==(const ShareableInformation& rhs) const {
  return

      (isIsShareable() == rhs.isIsShareable()) &&

      ((!capifProvDomsIsSet() && !rhs.capifProvDomsIsSet()) ||
       (capifProvDomsIsSet() && rhs.capifProvDomsIsSet() &&
        getCapifProvDoms() == rhs.getCapifProvDoms()))

          ;
}

bool ShareableInformation::operator!=(const ShareableInformation& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ShareableInformation& o) {
  j = nlohmann::json();
  j["isShareable"] = o.m_IsShareable;
  if (o.capifProvDomsIsSet() || !o.m_CapifProvDoms.empty())
    j["capifProvDoms"] = o.m_CapifProvDoms;
}

void from_json(const nlohmann::json& j, ShareableInformation& o) {
  j.at("isShareable").get_to(o.m_IsShareable);
  if (j.find("capifProvDoms") != j.end()) {
    j.at("capifProvDoms").get_to(o.m_CapifProvDoms);
    o.m_CapifProvDomsIsSet = true;
  }
}

bool ShareableInformation::isIsShareable() const { return m_IsShareable; }
void ShareableInformation::setIsShareable(bool const value) {
  m_IsShareable = value;
}
std::vector<std::string> ShareableInformation::getCapifProvDoms() const {
  return m_CapifProvDoms;
}
void ShareableInformation::setCapifProvDoms(
    std::vector<std::string> const& value) {
  m_CapifProvDoms = value;
  m_CapifProvDomsIsSet = true;
}
bool ShareableInformation::capifProvDomsIsSet() const {
  return m_CapifProvDomsIsSet;
}
void ShareableInformation::unsetCapifProvDoms() {
  m_CapifProvDomsIsSet = false;
}

}  // namespace org::openapitools::server::model
