/**
 * CAPIF_Publish_Service_API
 * API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * PublishServiceServerImpl.h
 *
 *
 */

#ifndef DEFAULT_API_IMPL_H_
#define DEFAULT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <mongocxx/client.hpp>
#include <mongocxx/instance.hpp>
#include <mongocxx/stdx.hpp>
#include <mongocxx/uri.hpp>
#include <string>

#include "capif/api/PublishServiceServer.h"
#include "capif/model/ProblemDetails.h"
#include "capif/model/ServiceAPIDescription.h"

namespace org::openapitools::server::api {

using namespace org::openapitools::server::model;

class PublishServiceServerImpl
    : public org::openapitools::server::api::PublishServiceServer {
 public:
  explicit PublishServiceServerImpl(
      const std::shared_ptr<Pistache::Rest::Router> &rtr,
      const std::shared_ptr<mongocxx::database> &database);
  ~PublishServiceServerImpl() override = default;

  void apf_id_service_apis_get(const std::string &apfId,
                               Pistache::Http::ResponseWriter &response);
  void apf_id_service_apis_post(
      const std::string &apfId,
      const ServiceAPIDescription &serviceAPIDescription,
      Pistache::Http::ResponseWriter &response);
  void apf_id_service_apis_service_api_id_delete(
      const std::string &serviceApiId, const std::string &apfId,
      Pistache::Http::ResponseWriter &response);
  void apf_id_service_apis_service_api_id_get(
      const std::string &serviceApiId, const std::string &apfId,
      Pistache::Http::ResponseWriter &response);
  void apf_id_service_apis_service_api_id_put(
      const std::string &serviceApiId, const std::string &apfId,
      const ServiceAPIDescription &serviceAPIDescription,
      Pistache::Http::ResponseWriter &response);

 private:
  std::shared_ptr<mongocxx::database> db;
};

}  // namespace org::openapitools::server::api

#endif
